# Generated by Django 5.2.9 on 2025-12-28 09:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FindRoomRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('property_type', models.CharField(choices=[('ROOM', 'Single Room'), ('FLAT', 'Flat/Apartment'), ('HOUSE', 'Full House'), ('ANY', 'Any Type')], max_length=20)),
                ('district', models.CharField(choices=[('KATHMANDU', 'Kathmandu'), ('BHAKTAPUR', 'Bhaktapur'), ('LALITPUR', 'Lalitpur')], max_length=20)),
                ('preferred_areas', models.TextField(help_text='Comma-separated list of preferred areas')),
                ('budget_range', models.CharField(choices=[('5000-10000', 'Rs. 5,000 - 10,000'), ('10000-15000', 'Rs. 10,000 - 15,000'), ('15000-20000', 'Rs. 15,000 - 20,000'), ('20000-30000', 'Rs. 20,000 - 30,000'), ('30000-50000', 'Rs. 30,000 - 50,000'), ('50000+', 'Rs. 50,000+')], max_length=20)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('move_in_date', models.DateField()),
                ('duration_months', models.PositiveIntegerField(default=12, help_text='Expected stay duration in months')),
                ('additional_requirements', models.TextField(blank=True, help_text='Any specific requirements')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWING', 'Under Review'), ('MATCHED', 'Matched'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='find_room_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Find Room Request',
                'verbose_name_plural': 'Find Room Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftHomeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('shift_type', models.CharField(choices=[('LOCAL', 'Within Same District'), ('INTER_DISTRICT', 'Between Districts'), ('OUTSIDE_VALLEY', 'Outside Kathmandu Valley')], max_length=20)),
                ('property_size', models.CharField(choices=[('ROOM', 'Single Room'), ('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('HOUSE', 'Full House')], max_length=20)),
                ('from_district', models.CharField(choices=[('KATHMANDU', 'Kathmandu'), ('BHAKTAPUR', 'Bhaktapur'), ('LALITPUR', 'Lalitpur'), ('OTHER', 'Other')], max_length=20)),
                ('from_area', models.CharField(max_length=100)),
                ('from_address', models.TextField()),
                ('to_district', models.CharField(choices=[('KATHMANDU', 'Kathmandu'), ('BHAKTAPUR', 'Bhaktapur'), ('LALITPUR', 'Lalitpur'), ('OTHER', 'Other')], max_length=20)),
                ('to_area', models.CharField(max_length=100)),
                ('to_address', models.TextField()),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(blank=True, max_length=50)),
                ('flexible_date', models.BooleanField(default=False)),
                ('has_heavy_items', models.BooleanField(default=False, help_text='Refrigerator, washing machine, etc.')),
                ('needs_packing', models.BooleanField(default=False, help_text='Need packing service?')),
                ('special_items', models.TextField(blank=True, help_text='Any special items that need careful handling')),
                ('additional_notes', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUOTED', 'Quote Sent'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_home_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift Home Request',
                'verbose_name_plural': 'Shift Home Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
