# Generated by Django 5.2.9 on 2025-12-31 00:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='findroomrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Room Request', 'verbose_name_plural': 'Room Requests'},
        ),
        migrations.RemoveField(
            model_name='findroomrequest',
            name='admin_notes',
        ),
        migrations.AddField(
            model_name='findroomrequest',
            name='title',
            field=models.CharField(default='Room Request', help_text='Short title for your room request', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='findroomrequest',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='findroomrequest',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('MATCHED', 'Matched'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='RoomRequestReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_request_replies', to=settings.AUTH_USER_MODEL)),
                ('property_link', models.ForeignKey(blank=True, help_text='Optionally link one of your properties', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_request_replies', to='properties.property')),
                ('room_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='services.findroomrequest')),
            ],
            options={
                'verbose_name': 'Room Request Reply',
                'verbose_name_plural': 'Room Request Replies',
                'ordering': ['-created_at'],
            },
        ),
    ]
