# Generated by Django 5.2.9 on 2025-12-28 09:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the property')),
                ('property_type', models.CharField(choices=[('ROOM', 'Room'), ('FLAT', 'Flat'), ('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('COMMERCIAL', 'Commercial Space')], default='ROOM', max_length=20)),
                ('district', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur')], default='Kathmandu', max_length=20)),
                ('area', models.CharField(help_text='e.g., Thamel, Basundhara, Jhamsikhel', max_length=100)),
                ('address', models.CharField(help_text='Full address/landmark', max_length=255)),
                ('google_maps_link', models.URLField(blank=True, null=True)),
                ('price_per_month', models.DecimalField(decimal_places=2, help_text='Monthly rent in Nepali Rupees', max_digits=10)),
                ('negotiable', models.BooleanField(default=False)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, help_text='Security deposit amount (optional)', max_digits=10, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(default=1)),
                ('bathrooms', models.PositiveSmallIntegerField(default=1)),
                ('floor_number', models.CharField(blank=True, help_text='e.g., Ground, 1st, 2nd', max_length=20)),
                ('total_floors', models.PositiveSmallIntegerField(default=1)),
                ('area_sq_ft', models.PositiveIntegerField(blank=True, help_text='Area in square feet', null=True)),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of amenity codes')),
                ('parking_available', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('preferred_tenant', models.CharField(blank=True, help_text='e.g., Family, Bachelor, Student, Any', max_length=50)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('minimum_stay_months', models.PositiveSmallIntegerField(default=6)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RENTED', 'Rented Out')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('inquiries_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order', '-is_primary', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='properties.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['district', 'status'], name='properties__distric_1ea38e_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'status'], name='properties__propert_487234_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price_per_month'], name='properties__price_p_0baf56_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'created_at'], name='properties__status_8e4eb2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'property')},
        ),
    ]
