# Generated by assistant - adds fraud fields and image_hash
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='fraud_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='flag_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
